include:
  - beszel/compose.yaml
  - beszel-agent/compose.yaml
  - beszel-agent-socket-proxy/compose.yaml
  - caddy/compose.yaml
  - dozzle/compose.yaml
  - dozzle-socket-proxy/compose.yaml
  - gatus/compose.yaml
  - gitea/compose.yaml
  - navidrome/compose.yaml
  - woodpecker-ci-agent/compose.yaml
  - woodpecker-ci-agent-socket-proxy/compose.yaml
  - woodpecker-ci-server/compose.yaml
