services:
  gatus:
    image: twinproduction/gatus:latest@sha256:0009b90a11c042809f7f988c05c3f398dbf24b7498a0b7083efe3b9e8e126550
    restart: unless-stopped
    volumes:
      - ./config.yaml:/config/config.yaml
