services:
  gatus:
    image: twinproduction/gatus:v5.36.0@sha256:c5f210d095fa78e6efaa20ffeb14803f2ba4f10615e16a6d12087697149617f0
    restart: unless-stopped
    volumes:
      - gatus_data:/data
      - ./config.yaml:/config/config.yaml
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
volumes:
  gatus_data:
