services:
  gatus:
    container_name: gatus
    image: twinproduction/gatus:v5.36.0
    restart: unless-stopped
    networks:
      - gatus_network
    volumes:
      - gatus_data:/data
      - ./config.yaml:/config/config.yaml
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
networks:
  gatus_network:
    external: true
volumes:
  gatus_data:
