services:
  gitea:
    container_name: gitea
    image: docker.gitea.com/gitea:1.27.2@sha256:d20286ca2b2e170fdf628e7231b8a31a3220ade39ff462b55041d43d1fc757dd
    restart: unless-stopped
    networks:
      - gitea_network
    volumes:
      - gitea_data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - GITEA__api__ENABLE_SWAGGER=false
      - GITEA__security__ALLOWED_HOST_LIST=loopback,private
      - GITEA__security__INSTALL_LOCK=true
      - GITEA__security__PASSWORD_HASH_ALGO=argon2
      - GITEA__security__TWO_FACTOR_AUTH=enforced
      - GITEA__server__DISABLE_SSH=true
      - GITEA__server__LANDING_PAGE=explore
      - GITEA__service__DEFAULT_KEEP_EMAIL_PRIVATE=true
      - GITEA__service__DISABLE_REGISTRATION=true
      - GITEA__ui__SHOW_USER_EMAIL=false
      - USER_UID=1000
      - USER_GID=1000
    security_opt:
      - no-new-privileges:true
    labels:
      - traefik.enable=true
      - traefik.http.routers.git.rule=Host(`git.ocd.beauty`)
      - traefik.http.routers.git.entrypoints=websecure
      - traefik.http.routers.git.tls=true
      - traefik.http.services.git.loadbalancer.server.port=3000
networks:
  gitea_network:
    external: true
volumes:
  gitea_data:
