services:
  navidrome:
    container_name: navidrome
    image: deluan/navidrome:0.63.2
    restart: unless-stopped
    networks:
      - navidrome_network
    volumes:
      - navidrome_data:/data
      - "/srv/navidrome/music:/music:ro"
      - "./navidrome.toml:/data/navidrome.toml:ro"
    user: 1000:1000
    security_opt:
      - no-new-privileges:true
networks:
  navidrome_network:
    external: true
volumes:
  navidrome_data:
