services:
  beszel-agent:
    image: henrygd/beszel-agent:latest@sha256:3b1939746690e423072b4a99bf4c4af6dd9562a68978a33738a3c4a4cc000c39
    restart: unless-stopped
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./beszel_agent_data:/var/lib/beszel-agent
      - ./beszel_socket:/beszel_socket
    environment:
      - LISTEN=/beszel_socket/beszel.sock
      - HUB_URL=http://localhost:8090
      - TOKEN=${TOKEN}
      - KEY=${KEY}
