services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:v10.7.3-alpine@sha256:f1ed2bbbcae850cf0d3fb8956535fdea766933dc24a24dfedc2c752b8b8a239f
    restart: unless-stopped
    networks:
      - dozzle_network
    volumes:
      - dozzle_data:/data
      - ./users.yaml:/data/users.yaml:ro
    ports:
      - "50495:8080"
    environment:
      - DOCKER_HOST=tcp://dozzle-socket-proxy:2375
      - DOZZLE_AUTH_PROVIDER=simple
      - DOZZLE_NO_ANALYTICS=true
networks:
  dozzle_network:
    external: true
volumes:
  dozzle_data:
