services:
  woodpecker-ci-server:
    image: woodpeckerci/woodpecker-server:v3@sha256:23bdea05bc35ce150d9ba768889c3f00b3a618785c85b268e8fbf9b06d5a21e0
    restart: unless-stopped
    volumes:
      - woodpecker-ci-server-data:/var/lib/woodpecker
    environment:
      - WOODPECKER_ADMIN=${WOODPECKER_ADMIN}
      - WOODPECKER_AGENT_SECRET=${WOODPECKER_AGENT_SECRET}
      - WOODPECKER_DEBUG_NOCOLOR=false
      - WOODPECKER_DEBUG_PRETTY=true
      - WOODPECKER_GITEA=true
      - WOODPECKER_GITEA_CLIENT=${WOODPECKER_GITEA_CLIENT}
      - WOODPECKER_GITEA_SECRET=${WOODPECKER_GITEA_SECRET}
      - WOODPECKER_GITEA_URL=${WOODPECKER_GITEA_URL}
      - WOODPECKER_GRPC_SECRET=${WOODPECKER_GRPC_SECRET}
      - WOODPECKER_HOST=${WOODPECKER_HOST}
      - WOODPECKER_OPEN=true
      - WOODPECKER_PLUGINS_PRIVILEGED=woodpeckerci/plugin-docker-buildx
  woodpecker-ci-agent:
    image: woodpeckerci/woodpecker-agent:v3@sha256:03c7b1f7b2156d00fdf4c30da77ac2bfe88d09ed818ea4627f82835ad81a98c9
    restart: unless-stopped
    volumes:
      - woodpecker-ci-agent-config:/etc/woodpecker
      - /var/run/docker.sock:/var/run/docker.sock
    command: agent
    environment:
      - WOODPECKER_AGENT_SECRET=${WOODPECKER_AGENT_SECRET}
      - WOODPECKER_DEBUG_NOCOLOR=false
      - WOODPECKER_DEBUG_PRETTY=true
      - WOODPECKER_SERVER=woodpecker-ci-server:9000
    depends_on:
      - woodpecker-ci-server
volumes:
  woodpecker-ci-agent-config:
  woodpecker-ci-server-data:
